POST http://localhost:3001/conversions
Content-Type: application/json

{
  "inputFile": {
    "name": "file.docx",
    "format": "docx"
  },
  "outputFile": {
    "format": "pdf"
  }
}

###

GET http://localhost:3001/conversions/ijqmm8mjxuh6n1rqqxpgyzbr
